# Generated by Django 2.2.6 on 2020-12-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20201214_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
        migrations.AddField(
            model_name='friend',
            name='borrower',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
