# Generated by Django 2.2.6 on 2020-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20201214_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='borrower',
        ),
    ]
